apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: dvd-api
  type: LoadBalancer # Esto nos dar√° una IP para entrar desde fuera
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvd-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvd-api
  template:
    metadata:
      labels:
        app: dvd-api
    spec:
      containers:
        - name: api
          image: my-dvd-api:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PGHOST
              value: "db-service" # Nombre del Service de la DB
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: "postgres"
            - name: PGDATABASE
              value: "dvdrental"
            - name: PGSSLMODE
              value: "disable"
